### ISSUE TITLE
ConventionalExtensions not automatically loading extensions for Active Record models

### ISSUE THREAD

**Issue by joelmoss** [kaspth/conventional_extensions#3]
According to the README...

> ConventionalExtensions automatically loads extensions for Active Record models.

But that isn't happening. So I have to manually add `load_extensions` in my models.

thx

**Comment by kaspth** [comment]
Ah of course, I didn't test the inherited hook all the way. I've fixed this in https://github.com/kaspth/conventional_extensions/commit/1f6fe9cbf2fe44ed9d699a5dd485eaa366d875a4, thank you for the issue.

**Comment by joelmoss** [comment]
Cheers! 👌
