### ISSUE TITLE
`dirname': no implicit conversion of false into String (TypeError)

### ISSUE THREAD

**Issue by joelmoss** [kaspth/conventional_extensions#4]
In 0.2.1...

```
lib/conventional_extensions/loader.rb:10:in `dirname': no implicit conversion of false into String (TypeError)
```

Seems the `path` arguments in `ConventionalExtensions::Loader#initialize` is `false` 🤔

**Comment by kaspth** [comment]
I don't know how to reproduce this from the issue. Can you make a reproduction sample?

**Comment by kaspth** [comment]
This indicates that `const_source_location(name).first` returns `false`, but Ruby's documentation doesn't mention that, so I still don't know how to reproduce this. Let me know when you have the reproduction sample.

**Comment by lsylvester** [comment]
I am also seeing this issue.

I have a repo that reproduces the issue for me at https://github.com/lsylvester/conventional_extensions_4. It isn't doing anything that is obviously causing the issue - so it may be environmental factors and not the particular code.

It seems it could be related to https://github.com/ruby/ruby/pull/5646

**Comment by lsylvester** [comment]
Error only occurs on zeitwerk 2.6.0. Fine on 2.5.4

**Comment by kaspth** [comment]
@lsylvester nice, thanks for the reproduction, I've pushed 0.2.2 which fixes this.

**Comment by joelmoss** [comment]
thx guys!
