### ISSUE TITLE
Namespaced classes

### ISSUE THREAD

**Issue by joelmoss** [kaspth/conventional_extensions#7]
Hiya 👋

Extensions don't seem to be loading for namespaced classes.

As an example, here is a `Organisation::User` AR model and an extension...

```ruby
# /app/models/organisation/user.rb
class Organisation::User < ApplicationRecord
end
```

```ruby
# /app/models/organisation/user/extensions/first_name.rb
class Organisation::User
  def first_name
    'Joel'
  end
end
```

Calling the `#first_name` method results in a `method_missing` exception...

```ruby
Organisation::User.new.first_name

# `method_missing': undefined method `first_name' for #<Organisation::User...
```

**Comment by kaspth** [comment]
Perfect, thank you! I've fixed this in #9 and I'll look at the remaining issue and hopefully ship a release soon.
