### ISSUE TITLE
Zeitwerk::NameError with Rails `eager_load` during tests

### ISSUE THREAD

**Issue by joelmoss** [kaspth/conventional_extensions#8]
In `config/environments/test.rb`, I have this line:

```ruby
config.eager_load = ENV['CI'].present?
```

When running my tests in CI, `ENV['CI']` is true, thus setting `eager_load` to `true`. Which then results in `Zeitwerk::NameError`...

```
expected file app/models/client/extensions/stripe.rb to define constant Client::Extensions::Stripe, but didn't (Zeitwerk::NameError)
```

`eager_load` is true in prod, so I'm half expecting the same exception (not actually tested that yet). But I'm assuming something is done to avoid that?

Anyway, thx again for an amazing lib. Any help would be appreciated.

**Comment by kaspth** [comment]
Ah, I guess we'll need some Zeitwerk specific config in here to have it ignore the extensions directories. That's gonna take some digging.

**Comment by joelmoss** [comment]
I can't help but thinking that this goes against the Ruby/Rails convention of file names mirroring the object name. I understand why you do it this way, but it some how doesn't feel right when I have a class named `Client` in a file `app/models/client/extensions/stripe.rb`.

**Comment by joeldrapper** [comment]
Should be able to use this https://github.com/fxn/zeitwerk#ignoring-parts-of-the-project

**Comment by kaspth** [comment]
@joeldrapper oh it was right in the README, lol. I thought I'd have to dig more, thank you!

**Comment by kaspth** [comment]
> I can't help but thinking that this goes against the Ruby/Rails convention of file names mirroring the object name. I understand why you do it this way, but it some how doesn't feel right when I have a class named `Client` in a file `app/models/client/extensions/stripe.rb`.

We can take a look at concrete suggestions for improvements? I like the current form though and I'm not going to spend time coming up with alternatives, just to be upfront.

**Comment by joelmoss** [comment]
Yeah don't get me wrong, I like it too. It's simple, and is what you would usually do when reopening a class, so makes sense in that regard. But I'm also wary of flying against well used convention - I've been burnt by that before 😏

Just thinking out loud here, but how about:

```ruby
# app/models/client/extensions/stripe.rb
class Client::Extensions::Stripe
  ...
end
```

This would mean sticking to convention, and also has a nice side affect of knowing where I am by looking at the class name, as well as at the file name.

🤔 What do ya think?

**Comment by joeldrapper** [comment]
You can define a class called `Client::Extensions::Stripe` but that doesn't automatically patch the `Client` class you're trying to extend. You’d have to go back to `ActiveSupport::Concern` modules with `class_methods` macro, which is exactly what conventional_extensions is designed to avoid.

I think there should be a way to get Zeitwerk to ignore the the pattern `**/extensions/**.rb`. Alternatively, perhaps there could be a naming convention for Zeitwerk ignored files, like an underscore prefix.

**Comment by kaspth** [comment]
@joelmoss thank you for the issue, I finally got around to fixing this.

@joeldrapper thank you for the ignore suggestion, it worked out!
